export const arrayOfProjects = [
  {
    link: "https://sveahemsidor.se/demo36/",
    name: "Business Corporate",
    image: "demo36.png",
    category: "Business",
  },
  {
    link: "https://sveahemsidor.se/demo33/",
    name: "Cleaning Services",
    image: "demo33.png",
    category: "Cleaning",
  },
  {
    link: "https://sveahemsidor.se/demo8/",
    name: "Archus",
    image: "demo8.png",
    category: "Construction",
  },
  {
    link: "https://sveahemsidor.se/demo10/",
    name: "Capitan Repair",
    image: "demo10.png",
    category: "Construction",
  },
  {
    link: "https://sveahemsidor.se/demo11/",
    name: "Trowel",
    image: "demo11.png",
    category: "Construction",
  },
  {
    link: "https://sveahemsidor.se/demo40/",
    name: "Bire Real Estate",
    image: "demo40.png",
    category: "Construction",
  },
  {
    link: "https://sveahemsidor.se/demo3/",
    name: "IT ideas",
    image: "demo3.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo5/",
    name: "Peakex",
    image: "demo5.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo13/",
    name: "Web App",
    image: "demo13.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo16/",
    name: "Analytics Landing Page",
    image: "demo16.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo19/",
    name: "Super Service Mockup",
    image: "demo19.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo20/",
    name: "Web Agency",
    image: "demo20.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo21/",
    name: "Fredo Saas Landing Page",
    image: "demo21.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo19/",
    name: "Go Hub",
    image: "demo24.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo26/",
    name: "Marketing Landing Page",
    image: "demo26.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo38/",
    name: "Event Jungle",
    image: "demo38.png",
    category: "Consulting",
  },
  {
    link: "https://sveahemsidor.se/demo25/",
    name: "Development Agency",
    image: "demo25.png",
    category: "Development",
  },
  {
    link: "https://sveahemsidor.se/demo29/",
    name: "Vertigo Web Development",
    image: "demo29.png",
    category: "Development",
  },
  {
    link: "https://sveahemsidor.se/demo42/",
    name: "Mobile App Landing Page",
    image: "demo42.png",
    category: "Development",
  },
  {
    link: "https://sveahemsidor.se/demo4/",
    name: "EarthPower",
    image: "demo4.png",
    category: "Electricity",
  },
  {
    link: "https://sveahemsidor.se/demo43/",
    name: "Fi-Nergy",
    image: "demo43.png",
    category: "Electricity",
  },
  {
    link: "https://sveahemsidor.se/demo2/",
    name: "MaestroPizzini",
    image: "demo2.png",
    category: "Food",
  },
  {
    link: "https://sveahemsidor.se/demo7/",
    name: "Bettaso",
    image: "demo7.png",
    category: "Food",
  },
  {
    link: "https://sveahemsidor.se/demo15/",
    name: "The Pizzerio",
    image: "demo15.png",
    category: "Food",
  },
  {
    link: "https://sveahemsidor.se/demo27/",
    name: "Restaurant",
    image: "/demo27.png",
    category: "Food",
  },
  {
    link: "https://sveahemsidor.se/demo28/",
    name: "Nectar Cafe",
    image: "demo28.png",
    category: "Food",
  },
  {
    link: "https://sveahemsidor.se/demo32/",
    name: "Resto",
    image: "demo32.png",
    category: "Food",
  },
  {
    link: "https://sveahemsidor.se/demo37/",
    name: "Coffee Shop",
    image: "demo37.png",
    category: "Food",
  },
  {
    link: "https://sveahemsidor.se/demo6/",
    name: "Alpha Health",
    image: "demo6.png",
    category: "Health",
  },
  {
    link: "https://sveahemsidor.se/demo39/",
    name: "Spa",
    image: "demo39.png",
    category: "Health",
  },
  {
    link: "https://sveahemsidor.se/demo12/",
    name: "Pet Food",
    image: "demo12.png",
    category: "Pet",
  },
  {
    link: "https://sveahemsidor.se/demo34/",
    name: "Photographer",
    image: "demo34.png",
    category: "Photo",
  },
  {
    link: "https://sveahemsidor.se/demo18/",
    name: "Portfolio",
    image: "demo18.png",
    category: "Portfolio",
  },
  {
    link: "https://sveahemsidor.se/demo23/",
    name: "Crezy Yoga",
    image: "demo23.png",
    category: "Sport",
  },
  {
    link: "https://sveahemsidor.se/demo41/",
    name: "Gym",
    image: "demo41.png",
    category: "Sport",
  },
  {
    link: "https://sveahemsidor.se/demo14/",
    name: "Education E-Learning",
    image: "demo14.png",
    category: "Study",
  },
  {
    link: "https://sveahemsidor.se/demo17/",
    name: "Education",
    image: "demo17.png",
    category: "Study",
  },
  {
    link: "https://sveahemsidor.se/demo22/",
    name: "Blatropt saas Landing Page",
    image: "demo22.png",
    category: "Study",
  },
  {
    link: "https://sveahemsidor.se/demo22/",
    name: "Travel Guide",
    image: "demo31.png",
    category: "Travel",
  },
  {
    link: "https://sveahemsidor.se/demo35/",
    name: "Wedding",
    image: "demo35.png",
    category: "Wedding",
  },
]

export const categories = [
  "Wedding",
  "Development",
  "Study",
  "Sport",
  "Portfolio",
  "Health",
  "Pet",
  "Food",
  "Consulting",
  "Business",
  "Cleaning",
  "Construction",
  "Electricity",
  "Photo",
]
